####
# Example of what CKEditor can all bring
###

# Load default processing options
imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:
  config:
    contentsCss: "EXT:tmpl_ipoa/Resources/Public/Css/rte.css"
    format_tags: 'p;h3;h4;ondemandlink;ondemandcontent'
    format_ondemandlink: { name: "On demand link", element: "div", attributes: { class: "on-demand__link" } }
    format_ondemandcontent: { name: "On demand content", element: "div", attributes: { class: "on-demand__content" } }
    toolbarGroups:
      - { name: clipboard, groups: [clipboard, undo] }
      - { name: editing,   groups: [find, selection, spellchecker] }
      - { name: links }
      - { name: insert }
      - { name: tools }
      - { name: table }
      - { name: tabletools }
      - { name: document,  groups: [ mode, document, doctools ] }
      - { name: others }
      - "/"
      - { name: basicstyles, groups: [ basicstyles, align, cleanup ] }
      - { name: paragraph,   groups: [ list, indent, blocks, align, bidi ] }
      - { name: specialcharacters,   groups: [ insertcharacters ] }
      - "/"
      - { name: styles }

    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify

    extraPlugins:
      - justify
      - find
      - selectall

    removePlugins:
      - image

    removeButtons:
      - Underline
      - Strike
      - Table
      - HorizontalRule

# Allow s and u tag
processing:
  allowTags:
    - s
    - u
